version: '3.8'

services:
  modbusim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    ports:
      - "5020:5020"
      - "5021:5021"  # Additional port for testing
    working_dir: /app
    tty: true
    stdin_open: true
